name: ${project.name}
description: ${project.description}
author: Fahrenheit451|Capri205
website: ${project.url}
version: ${project.version}
api-version: ${api-version}
main: net.obmc.${project.name}.${project.name}
commands:
  obspawn:
    description: Main command for setting a spawn for a world
    usage: Use /obspawn for usage
    aliases: obs
